### PR TITLE
Fixed Bug-6304 Wrong link for downloading .NET Framework 4.0

### PR DESCRIPTION
**Pull request by gitexperience**
The link here redirects to the windows sdk download page , i have fixed it to the download page of .net framework

### CODE REVIEW

**Comment by Therzok** [comment]
We exclusively require .NET 4.5 for a while now. Please update to that link.

**Comment by gitexperience** [comment]
link changed !!

**Comment by Therzok** [comment]
Thanks

**Comment by akoeplinger** [comment]
Since 4.5 is technically old as well, I updated it to the 4.5.2 download link :smile:

**Pull request merged**
